---
# file: ansible-role-node-exporter/tasks/main.yaml

- include_role:
    name: ansible-role-reverse-proxy
  vars:
    nginx_proxy_pass: http://localhost:9100
    nginx_data_dir: /opt/nginx-exporter-proxy
    nginx_container_port: 8444:443
    nginx_container_name: nginx-exporter-proxy

- name: Download exporter
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version | default("0.17.0") }}/node_exporter-{{ node_exporter_version | default("0.17.0") }}.linux-amd64.tar.gz
    dest: /opt/exporter_{{ node_exporter_version | default("0.17.0") }}.tar.gz
  register: download

- name: Untar exporter
  unarchive:
    src: /opt/exporter_{{ node_exporter_version | default("0.17.0")}}.tar.gz
    remote_src: yes
    dest: /opt
    extra_opts: [--strip-components=1]
  when: download is changed

- name: Copy executable to PATH
  copy:
    src: /opt/node_exporter
    remote_src: yes
    dest: /usr/bin/node_exporter
    owner: root
    group: root
    mode: 755
  when: download is not skipped 

- name: Create systemd service
  copy: 
    src: node_exporter.service
    dest: /lib/systemd/system/node_exporter.service
    mode: 644
    owner: root
    group: root

- name: Start node_exporter
  service:
    name: node_exporter
    state: started
    enabled: yes


