---
# file: ansible-role-node-exporter/tasks/main.yaml

- name: Check if node_exporter exists
  stat: path=/usr/bin/node_exporter
  register: node_exporter
 
- name: Download exporter
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v0.17.0/node_exporter-0.17.0.linux-amd64.tar.gz
    dest: /opt/exporter.tar.gz
  register: download
  when: not node_exporter.stat.exists

- name: Untar exporter
  unarchive:
    src: /opt/exporter.tar.gz
    remote_src: yes
    dest: /opt
    extra_opts: [--strip-components=1]
  when: download is not skipped

- name: Copy executable to PATH
  copy:
    src: /opt/node_exporter
    remote_src: yes
    dest: /usr/bin/node_exporter
    owner: root
    group: root
    mode: 755
  when: download is not skipped 

- name: Create systemd service
  copy: 
    src: node_exporter.service
    dest: /lib/systemd/system/node_exporter.service
    mode: 644
    owner: root
    group: root

- name: Start node_exporter
  service:
    name: node_exporter
    state: started
