---
# file: ansible-role-node-exporter/tasks/main.yaml

- name: Create role directory
  file:
    path: "{{ node_exporter_data_dir }}"
    state: directory

- name: Download exporter
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_exporter_version }}/node_exporter-{{ node_exporter_exporter_version }}.linux-amd64.tar.gz
    dest: "{{ node_exporter_data_dir }}/exporter_{{ node_exporter_exporter_version }}.tar.gz"
  register: download

#- name: Install exporter
#  block:
- name: Untar exporter
  unarchive:
    src: "{{ node_exporter_data_dir }}/exporter_{{ node_exporter_exporter_version }}.tar.gz"
    remote_src: yes
    dest: "{{ node_exporter_data_dir }}"
    extra_opts: [--strip-components=1]

- name: Copy executable to PATH
  copy:
    src: "{{ node_exporter_data_dir }}/node_exporter"
    remote_src: yes
    dest: /usr/local/bin/node_exporter
    owner: root
    group: root
    mode: 0755
  notify: node_exporter_systemd_restart
#  when: download is changed

- name: Create node_exporter user/group
  group:
    name: node_exporter
- user:
    name: node_exporter
    groups: node_exporter
    shell: /sbin/nologin

- name: Check if docker is installed
  command: docker --version
  register: docker
  changed_when: false
  failed_when: false
  check_mode: no

- block:
  - name: Check if reverse proxy continer is running
    shell: docker ps -a -q --filter "label={{ node_exporter_reverse_proxy }}"
    register: reverse_proxy
    changed_when: false
    check_mode: no

  - name: Configure reverse proxy
    template:
      src: exporter.https.location.j2
      dest: "{{ node_exporter_proxy_data_dir }}/conf.d/{{ role_name }}.https.location"
      owner: root
      mode: 0600
    notify: reverse_proxy_nginx_restart
    when: not reverse_proxy.stdout == ""

  when: docker.rc == 0

- name: Config without proxy
  set_fact: node_exporter_listen_address="0.0.0.0:9100"
  when: docker.rc != 0

- name: Create systemd service. Listens on {{ node_exporter_listen_address }}
  template: 
    src: node_exporter.service.j2
    dest: /lib/systemd/system/node_exporter.service
    mode: 0644
    owner: root
    group: root
  notify: node_exporter_systemd_restart

- name: add sys updates metrics
  include_tasks: monitor_updates.yaml
  when: node_exporter_metrics_updates
 
- name: add ovpn metrics
  include_tasks: ovpn_exporter.yaml
  when: node_exporter_export_ovpn
 
- name: enable service
  systemd:
    state: started
    enabled: true
    daemon_reload: yes
    name: node_exporter

- name: enable service
  systemd:
    state: started
    enabled: true
    daemon_reload: yes
    name: openvpn_exporter
