---
# file: ansible-role-node-exporter/tasks/main.yaml

- include_role:
    name: ansible-role-reverse-proxy
  vars:
    nginx_proxy_pass: http://localhost:9100
    nginx_data_dir: /opt/nginx-exporter-proxy
    nginx_container_port: "80:80" 
    nginx_container_name: nginx-exporter-proxy
    nginx_container_network: host
    allowedHosts: ['127.0.0.1', '172.16.0.0/12']

- name: Download exporter
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
    dest: /opt/exporter_{{ node_exporter_version }}.tar.gz
  register: download

- name: Untar exporter
  unarchive:
    src: /opt/exporter_{{ node_exporter_version }}.tar.gz
    remote_src: yes
    dest: /opt
    extra_opts: [--strip-components=1]
  when: download is changed

- name: Copy executable to PATH
  copy:
    src: /opt/node_exporter
    remote_src: yes
    dest: /usr/bin/node_exporter
    owner: root
    group: root
    mode: 0755
  when: download is not skipped 

- name: Create systemd service
  copy: 
    src: node_exporter.service
    dest: /lib/systemd/system/node_exporter.service
    mode: 0644
    owner: root
    group: root
  register: exporter_service

- name: Update systemd if service is changed
  shell: systemctl daemon-reload && systemctl restart node_exporter
  when: exporter_service is changed

- name: Start node_exporter
  service:
    name: node_exporter
    state: started
    enabled: yes

- name: Create metrics folder
  file:
    path: /opt/metrics
    state: directory

- name: Create Cron job to get number of security updates
  cron:
    name: get security updates
    hour: 12
    user: root
    job: echo node_package_security_updates $(apt-get upgrade -s | grep -i "security" | wc -l) > /opt/metrics/node_package_security_updates.prom
    cron_file: prometheus_security_updates


- name: Create Cron job to get updates count
  cron:
    name: get updates
    hour: 12
    user: root
    job: echo node_package_updates $(apt-get upgrade -s |grep -P '^\d+ upgraded'|cut -d " " -f1) > /opt/metrics/node_package_updates.prom
    cron_file: prometheus_security_updates

