- name: Make sure metrics dir exist
  file: 
    path: "{{ node_exporter_prometheus_metrics }}"
    state: directory

- name: Copy openvpn exporter script to path
  copy:
    src: openvpn_exporter
    dest: "{{ node_exporter_ovpn_exec }}"
    mode: 0744

- name: Install systemd service for node exporter
  template:
    src: openvpn_exporter.service.j2
    dest: /etc/systemd/system/openvpn_exporter.service
