---
# file: ansible-role-node-exporter/tasks/uninstall.yaml

- name: Remove Cron job to get updates count
  cron:
    name: get updates
    hour: 12
    minute: 0
    user: root
    job: echo node_package_updates $(apt-get upgrade -s |grep -P '^\d+ upgraded'|cut -d " " -f1) > /opt/metrics/node_package_updates.prom
    cron_file: prometheus_security_updates
    state: absent

- name: Remove cron file 
  file:
    path: /etc/cron.d/prometheus_security_updates
    state: absent

- name: Remove Cron job to get number of security updates
  cron:
    name: get security updates
    hour: 12
    minute: 0
    user: root
    job: echo node_package_security_updates $(apt-get upgrade -s | grep -i "security" | wc -l) > /opt/metrics/node_package_security_updates.prom
    cron_file: prometheus_security_updates
    state: absent

- name: Remove metrics folder
  file:
    path: /opt/metrics
    state: absent

- name: Stop node_exporter
  service:
    name: node_exporter
    state: stopped
    enabled: no
  ignore_errors: true

- name: Remove systemd service
  file: 
    path: /lib/systemd/system/node_exporter.service
    state: absent

- name: Update systemd if service is changed
  shell: systemctl daemon-reload 

- name: Remove executable from PATH
  file:
    path: /usr/bin/node_exporter
    state: absent

- name: Remove executable from opt
  file:
    path: /opt/node_exporter
    state: absent

- name: Remove LICENSE from opt
  file:
    path: /opt/LICENSE
    state: absent

- name: Remove NOTICE from opt
  file:
    path: /opt/NOTICE
    state: absent

- name: Remove archive
  file:
    path: /opt/exporter_{{ node_exporter_version }}.tar.gz
    state: absent

- include_role:
    name: ansible-role-reverse-proxy
    tasks_from: uninstall
  vars:
    nginx_proxy_pass: http://localhost:9100
    nginx_data_dir: /opt/nginx-exporter-proxy
    nginx_container_port: "80:80" 
    nginx_container_name: nginx-exporter-proxy
    nginx_container_network: host
    allowedHosts: ['127.0.0.1', '172.16.0.0/12']

