- name: Make sure metrics dir exist
  file: 
    path: "{{ node_exporter_prometheus_metrics }}"
    state: directory

- name: Copy wifi exporter script to path
  copy:
    src: wifi_exporter
    dest: "{{ node_exporter_wifi_exec }}"
    mode: 0744

- name: Install systemd service for wifi exporter
  template:
    src: wifi_exporter.service.j2
    dest: /etc/systemd/system/wifi_exporter.service
